GEMINI_API_KEY = "AIzaSyDya5MCCXN6QgsYBWeW93ZaO_5CkuXogTk"
GOOGLE_VISION_API_KEY = "AIzaSyC5aageWFdZSuOQc21jU9YUcgGgV2V-qRA"
BACKUP_KEY = "AIzaSyC8VMuyqls-RPGnJq7OoAJ_2rNR0zJDAW0"
MONGO_URI = "mongodb+srv://kiet410pham_db_user:kiet04102003@cluster0.xcuzaq0.mongodb.net/?appName=Cluster0"
